name: Snowflake_Setup

on:
  push:
    branches:
      - main
      - dev
      - qa
      - prod

jobs:
  setup-snowflake-roles-and-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SnowSQL CLI
        uses: snowflakedb/snowflake-cli-action@v1
        with:
          version: "latest"

      - name: Configure Snowflake connection
        run: |
          echo "[connections]" > ~/.snowsql/config
          echo "accountname = ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.snowsql/config
          echo "username = ${{ secrets.SNOWFLAKE_USER }}" >> ~/.snowsql/config
          echo "password = ${{ secrets.SNOWFLAKE_PASSWORD }}" >> ~/.snowsql/config
          echo "role = ${{ secrets.SNOWFLAKE_ROLE }}" >> ~/.snowsql/config
          echo "warehouse = ${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> ~/.snowsql/config
          echo "database = ${{ secrets.SNOWFLAKE_DATABASE }}" >> ~/.snowsql/config
          echo "schema = ${{ secrets.SNOWFLAKE_SCHEMA }}" >> ~/.snowsql/config
          
      - name: Create roles and users for dev, qa, prod
        run: |
          environment=${GITHUB_REF##*/}
          
          if [ "$environment" == "dev" ]; then
            echo "Setting up roles and users for DEV environment..."
            snowsql -f ./scripts/create_roles_and_users_dev.sql
          elif [ "$environment" == "qa" ]; then
            echo "Setting up roles and users for QA environment..."
            snowsql -f ./scripts/create_roles_and_users_qa.sql
          elif [ "$environment" == "prod" ]; then
            echo "Setting up roles and users for PROD environment..."
            snowsql -f ./scripts/create_roles_and_users_prod.sql
          else
            echo "Unknown environment: $environment"
            exit 1
          fi
